spring.application.name=sistema-estoque-pedidos

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/estoque_db
spring.datasource.username=estoque_app
spring.datasource.password=${ESTOQUE_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true