CREATE TABLE produtos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(50) NOT NULL,
    nome VARCHAR(120) NOT NULL,
    preco NUMERIC(12, 2) NOT NULL,
    quantidade_estoque INTEGER NOT NULL DEFAULT 0,
    estoque_minimo INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT uk_produtos_codigo UNIQUE (codigo),
    CONSTRAINT ck_produtos_codigo_preenchido
        CHECK (LENGTH(TRIM(codigo)) > 0),
    CONSTRAINT ck_produtos_nome_preenchido
        CHECK (LENGTH(TRIM(nome)) > 0),
    CONSTRAINT ck_produtos_preco
        CHECK (preco >= 0),
    CONSTRAINT ck_produtos_quantidade_estoque
        CHECK (quantidade_estoque >= 0),
    CONSTRAINT ck_produtos_estoque_minimo
        CHECK (estoque_minimo >= 0)
);