CREATE TABLE movimentacoes_estoque (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto_id BIGINT NOT NULL,
    tipo VARCHAR(10) NOT NULL,
    quantidade INTEGER NOT NULL,
    saldo_anterior INTEGER NOT NULL,
    saldo_posterior INTEGER NOT NULL,
    motivo VARCHAR(255) NOT NULL,
    data_movimentacao TIMESTAMP WITH TIME ZONE
        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_movimentacoes_produto
        FOREIGN KEY (produto_id) REFERENCES produtos (id),

    CONSTRAINT ck_movimentacoes_tipo
        CHECK (tipo IN ('ENTRADA', 'SAIDA')),

    CONSTRAINT ck_movimentacoes_quantidade
        CHECK (quantidade > 0),

    CONSTRAINT ck_movimentacoes_saldo_anterior
        CHECK (saldo_anterior >= 0),

    CONSTRAINT ck_movimentacoes_saldo_posterior
        CHECK (saldo_posterior >= 0),

    CONSTRAINT ck_movimentacoes_motivo
        CHECK (LENGTH(TRIM(motivo)) > 0),

    CONSTRAINT ck_movimentacoes_variacao_saldo
        CHECK (
            (
                tipo = 'ENTRADA'
                AND saldo_posterior::BIGINT =
                    saldo_anterior::BIGINT + quantidade::BIGINT
            )
            OR
            (
                tipo = 'SAIDA'
                AND saldo_posterior::BIGINT =
                    saldo_anterior::BIGINT - quantidade::BIGINT
            )
        )
);

CREATE INDEX idx_movimentacoes_produto_data
    ON movimentacoes_estoque (
        produto_id,
        data_movimentacao DESC,
        id DESC
    );