CREATE TABLE pedidos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente VARCHAR(120) NOT NULL,
    status VARCHAR(15) NOT NULL DEFAULT 'RASCUNHO',
    data_criacao TIMESTAMP WITH TIME ZONE
        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_confirmacao TIMESTAMP WITH TIME ZONE,
    data_cancelamento TIMESTAMP WITH TIME ZONE,

    CONSTRAINT ck_pedidos_cliente
        CHECK (LENGTH(TRIM(cliente)) > 0),

    CONSTRAINT ck_pedidos_status
        CHECK (status IN ('RASCUNHO', 'CONFIRMADO', 'CANCELADO')),

    CONSTRAINT ck_pedidos_datas_status
        CHECK (
            (
                status = 'RASCUNHO'
                AND data_confirmacao IS NULL
                AND data_cancelamento IS NULL
            )
            OR
            (
                status = 'CONFIRMADO'
                AND data_confirmacao IS NOT NULL
                AND data_cancelamento IS NULL
            )
            OR
            (
                status = 'CANCELADO'
                AND data_cancelamento IS NOT NULL
            )
        )
);

CREATE TABLE itens_pedido (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id BIGINT NOT NULL,
    produto_id BIGINT NOT NULL,
    quantidade INTEGER NOT NULL,
    preco_unitario NUMERIC(12, 2) NOT NULL,

    CONSTRAINT fk_itens_pedido_pedido
        FOREIGN KEY (pedido_id) REFERENCES pedidos (id),

    CONSTRAINT fk_itens_pedido_produto
        FOREIGN KEY (produto_id) REFERENCES produtos (id),

    CONSTRAINT uk_itens_pedido_produto
        UNIQUE (pedido_id, produto_id),

    CONSTRAINT ck_itens_pedido_quantidade
        CHECK (quantidade > 0),

    CONSTRAINT ck_itens_pedido_preco
        CHECK (preco_unitario >= 0)
);

CREATE INDEX idx_pedidos_status_id
    ON pedidos (status, id);

CREATE INDEX idx_itens_pedido_produto
    ON itens_pedido (produto_id);